### ISSUE TITLE
Elastic agente not register when a use secrets. 

### ISSUE THREAD

**Issue by PauloJFCabral** [gocd/gocd-kubernetes-based-secrets-plugin#145]
Hi 
I am with a problem using secrets in my pipeline. When I set the environment variable with Kubernetes secrete the gocd agent can't register. 
The agent is running in the same cluster and namespace that I create the secrets.

In the logs I can see the erro bellow: 

<code>
jvm 1    | 2022-07-04 15:55:35,358 [stdout] - }]
jvm 1    | 2022-07-04 15:55:35,359 [stdout] - 2022-07-04 15:55:35,359 ERROR [scheduler-3] AgentHTTPClientController:114 - Error occurred when agent tried to ping server: 
jvm 1    | 2022-07-04 15:55:35,359 [stdout] - java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
jvm 1    | 2022-07-04 15:55:35,359 [stdout] -    - This agent has been deleted from the configuration
jvm 1    | 2022-07-04 15:55:35,360 [stdout] -    - This agent is pending approval
jvm 1    | 2022-07-04 15:55:35,360 [stdout] -    - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/21.3.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:118)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.ping(RemotingClient.java:74)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.ping(AgentHTTPClientController.java:109)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - Caused by: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
jvm 1    | 2022-07-04 15:55:35,360 [stdout] -    - This agent has been deleted from the configuration
jvm 1    | 2022-07-04 15:55:35,360 [stdout] -    - This agent is pending approval
jvm 1    | 2022-07-04 15:55:35,360 [stdout] -    - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/21.3.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.validateResponse(RemotingClient.java:141)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:114)
jvm 1    | 2022-07-04 15:55:35,360 [stdout] - 	... 14 common frames omitted
jvm 1    | 2022-07-04 15:55:36,731 [stdout] - 2022-07-04 15:55:36,731 INFO  [main] DefaultPluginJarChangeListener:74 - Plugin load finished: /go/plugins/external/script-executor-0.3.0.jar
jvm 1    | 2022-07-04 15:55:36,755 [stdout] - 2022-07-04 15:55:36,753 INFO  [main] DefaultPluginJarChangeListener:67 - Plugin load starting: /go/plugins/external/git-fb-poller-1.3.5.jar
jvm 1    | 2022-07-04 15:55:40,374 [stdout] - 2022-07-04 15:55:40,373 ERROR [scheduler-3] RemotingClient:166 - Server responded to action `ping` with: status[422 Unprocessable Entity], body[{
jvm 1    | 2022-07-04 15:55:40,374 [stdout] -   "message" : "Agent [Agent [gocd-agent-4c2d8264-2f0c-40c7-80dc-ad0795a7edaa, 100.64.47.94, 0b79105e-8809-41ce-94d7-02087e7930d2, null]] has no cookie set; nested exception is com.thoughtworks.go.server.service.AgentNoCookieSetException: Agent [Agent [gocd-agent-4c2d8264-2f0c-40c7-80dc-ad0795a7edaa, 100.64.47.94, 0b79105e-8809-41ce-94d7-02087e7930d2, null]] has no cookie set"
jvm 1    | 2022-07-04 15:55:40,374 [stdout] - }]
</code>

Thank you for your help

**Comment by chadlwilson** [comment]
I can't see anything there that seems to relate to an issue with the plugin. The secrets plugins mainly work on the server side where server retrieves the secret (from k8s in this case), encrypts with a key known to the agents and then distributes them to the relevant agents, so I don't think this is an issue specific to the plugin.

This looks more like a general issue with agent registration. You might be better to describe specifically what you have configured and the problem somewhere like the forums at https://groups.google.com/g/go-cd where there is a bigger audience to help.
